//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Core.Host.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Core.Host.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating dataset [{0}]..
        /// </summary>
        internal static string DatasetProxy_LogMessage_ActivatingDataset_WithId {
            get {
                return ResourceManager.GetString("DatasetProxy_LogMessage_ActivatingDataset_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of dataset [{0}] was successful..
        /// </summary>
        internal static string DatasetProxy_LogMessage_DatasetActivationComplete_WithId {
            get {
                return ResourceManager.GetString("DatasetProxy_LogMessage_DatasetActivationComplete_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating dataset [{0}]..
        /// </summary>
        internal static string DatasetProxy_LogMessage_DeactivatingDataset_WithId {
            get {
                return ResourceManager.GetString("DatasetProxy_LogMessage_DeactivatingDataset_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate dataset [{0}]. Exception was: {1}..
        /// </summary>
        internal static string DatasetProxy_LogMessage_FailedToActivateDataset_WithException {
            get {
                return ResourceManager.GetString("DatasetProxy_LogMessage_FailedToActivateDataset_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivating dataset [{0}] on previously stored location: {1}..
        /// </summary>
        internal static string DatasetProxy_LogMessage_ReactivatingFromPreviouslyStoredLocation_WithLocation {
            get {
                return ResourceManager.GetString("DatasetProxy_LogMessage_ReactivatingFromPreviouslyStoredLocation_WithLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range. The argument value was: {0}..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dataset cannot be activated without a preferred distribution location..
        /// </summary>
        internal static string Exceptions_Messages_CannotActivateDatasetWithoutDistributionLocation {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotActivateDatasetWithoutDistributionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to activate a dataset without a target machine..
        /// </summary>
        internal static string Exceptions_Messages_CannotActivateDatasetWithoutTargetMachine {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotActivateDatasetWithoutTargetMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare these objects: {0} and {1}.
        /// </summary>
        internal static string Exceptions_Messages_CannotCompareUnequalTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCompareUnequalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid ID number..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateAMessageWithoutId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateAMessageWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid sender name..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateAMessageWithoutSender {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateAMessageWithoutSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dataset cannot be created without a creator..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateDatasetWithoutCreator {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateDatasetWithoutCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of the application does not allow the creation of a new project..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateNewProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a project without a dataset distribution function..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateProjectWithoutDatasetDistributor {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateProjectWithoutDatasetDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a project without a timeline..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateProjectWithoutTimeline {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateProjectWithoutTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified dataset cannot be deleted..
        /// </summary>
        internal static string Exceptions_Messages_CannotDeleteDataset {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotDeleteDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified dataset (with ID: {0}) cannot be deleted..
        /// </summary>
        internal static string Exceptions_Messages_CannotDeleteDataset_WithDatasetId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotDeleteDataset_WithDatasetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to run multiple scripts at the same time. Please stop the currently executing script before trying to run another script..
        /// </summary>
        internal static string Exceptions_Messages_CannotInteruptRunningScript {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotInteruptRunningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of the application does not allow the loading of an existing project..
        /// </summary>
        internal static string Exceptions_Messages_CannotLoadProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to log a message if the LogLevel is set to None..
        /// </summary>
        internal static string Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message where both the sender and the recipient are the same. The provided name was {0}..
        /// </summary>
        internal static string Exceptions_Messages_CannotSendAMessageBackToTheSender_WithDnsName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotSendAMessageBackToTheSender_WithDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message that is send to nobody..
        /// </summary>
        internal static string Exceptions_Messages_CannotSendAMessageToNoService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotSendAMessageToNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot uninstall the service. The provided service is not the service which is installed. Please use the original service when uninstalling..
        /// </summary>
        internal static string Exceptions_Messages_CannotUninstallNonEquivalentService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotUninstallNonEquivalentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current project cannot be unloaded..
        /// </summary>
        internal static string Exceptions_Messages_CannotUnloadProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotUnloadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dataset cannot be used after it has become invalid..
        /// </summary>
        internal static string Exceptions_Messages_CannotUseDatasetAfterItBecomesInvalid {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotUseDatasetAfterItBecomesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project cannot be used after it has been closed..
        /// </summary>
        internal static string Exceptions_Messages_CannotUseProjectAfterClosingIt {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotUseProjectAfterClosingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset with ID: {0} cannot be made a parent..
        /// </summary>
        internal static string Exceptions_Messages_DatasetCannotBecomeParent_WithId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DatasetCannotBecomeParent_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the online information for the given dataset because it is not activated..
        /// </summary>
        internal static string Exceptions_Messages_DatasetNotActivated {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DatasetNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given contract name is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateContractName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateDnsName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name. The name is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_DuplicateDnsName_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with the given ID has already been registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateGroupDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateGroupDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part with the given type identity is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicatePartDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicatePartDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type with the given type identity is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateTypeDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a new project failed..
        /// </summary>
        internal static string Exceptions_Messages_FailedToCreateProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FailedToCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of the specified project failed. .
        /// </summary>
        internal static string Exceptions_Messages_FailedToLoadProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FailedToLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write a log entry for log type: {0}.
        /// </summary>
        internal static string Exceptions_Messages_IncorrectLogType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is incorrect. Expected {0}, got {1}..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectType_WithTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectType_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. The error code is: {0}. Please contact your vendor..
        /// </summary>
        internal static string Exceptions_Messages_InternalError_WithCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InternalError_WithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path is not a valid path to the plugin directory..
        /// </summary>
        internal static string Exceptions_Messages_InvalidPluginDirectoryPath {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidPluginDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given script language is not a valid choice..
        /// </summary>
        internal static string Exceptions_Messages_InvalidScriptLanguage {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidScriptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given script language {0} cannot be used..
        /// </summary>
        internal static string Exceptions_Messages_InvalidScriptLanguage_WithLanguage {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidScriptLanguage_WithLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service failed..
        /// </summary>
        internal static string Exceptions_Messages_KernelServiceStartupFailed {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelServiceStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service of type {0} failed..
        /// </summary>
        internal static string Exceptions_Messages_KernelServiceStartupFailed_WithService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelServiceStartupFailed_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency..
        /// </summary>
        internal static string Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency. Service of type {0} missed a dependency..
        /// </summary>
        internal static string Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified log type has no logger registered..
        /// </summary>
        internal static string Exceptions_Messages_LogTypeHasNoLogger {
            get {
                return ResourceManager.GetString("Exceptions_Messages_LogTypeHasNoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log type {0} has no logger registered..
        /// </summary>
        internal static string Exceptions_Messages_LogTypeHasNoLogger_WithLogType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_LogTypeHasNoLogger_WithLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create one or more dataset without creation information..
        /// </summary>
        internal static string Exceptions_Messages_MissingCreationInformation {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingCreationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no notification action registered for the given notification name..
        /// </summary>
        internal static string Exceptions_Messages_MissingNotificationAction {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingNotificationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no notification action registered for the notification with name {0}..
        /// </summary>
        internal static string Exceptions_Messages_MissingNotificationAction_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingNotificationAction_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A missing service dependency was detected. The requested action cannot be performed..
        /// </summary>
        internal static string Exceptions_Messages_MissingServiceDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be at least size of 1..
        /// </summary>
        internal static string Exceptions_Messages_MustBufferMoreThanZeroMessages {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MustBufferMoreThanZeroMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be at least size of 1. The specified size was {0}..
        /// </summary>
        internal static string Exceptions_Messages_MustBufferMoreThanZeroMessages_WithCount {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MustBufferMoreThanZeroMessages_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time step for buffer flushing must be a positive number larger than zero. The specified time step was {0}..
        /// </summary>
        internal static string Exceptions_Messages_MustFlushAfterPositiveTimestep_WithTimestep {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MustFlushAfterPositiveTimestep_WithTimestep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current project. It is not possible to adjust the properties of the current project or any of its datasets..
        /// </summary>
        internal static string Exceptions_Messages_NoCurrentProject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no known message pipeline object..
        /// </summary>
        internal static string Exceptions_Messages_PipelineObjectMissing {
            get {
                return ResourceManager.GetString("Exceptions_Messages_PipelineObjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given script failed to execute..
        /// </summary>
        internal static string Exceptions_Messages_ScriptExecutionFailure {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ScriptExecutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender DNS name cannot be equivalent to the Nobody DNS name.
        /// </summary>
        internal static string Exceptions_Messages_SenderCannotBeNobody {
            get {
                return ResourceManager.GetString("Exceptions_Messages_SenderCannotBeNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have the KernelService type as dependency..
        /// </summary>
        internal static string Exceptions_Messages_ServiceCannotDependOnGenericKernelService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceCannotDependOnGenericKernelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have its own type as dependency..
        /// </summary>
        internal static string Exceptions_Messages_ServiceCannotDependOnItself {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceCannotDependOnItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service tried to perform an action while it was not in a working state. The actual state was: {0}.
        /// </summary>
        internal static string Exceptions_Messages_ServicesIsNotFullyFunctional {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServicesIsNotFullyFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service object of the given type is already installed..
        /// </summary>
        internal static string Exceptions_Messages_ServiceTypeAlreadyInstalled {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceTypeAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownDataset {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset with ID: {0} is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownDataset_WithId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDataset_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownDnsName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown. The name is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_UnknownDnsName_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested group definition is not registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownGroupDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownGroupDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel service of the given type is installed..
        /// </summary>
        internal static string Exceptions_Messages_UnknownKernelServiceType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownKernelServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified notification name is a duplicate of another notification name..
        /// </summary>
        internal static string Exceptions_Messages_UnknownNotificationName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownNotificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified notification name is a duplicate of another notification name. The name is {0}..
        /// </summary>
        internal static string Exceptions_Messages_UnknownNotificationName_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownNotificationName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested part definition is not registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownPartDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownPartDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given ID does not belong to a known part group..
        /// </summary>
        internal static string Exceptions_Messages_UnknownPartGroup {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownPartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested type definition is not registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownTypeDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license verification has failed. Please contact your vendor..
        /// </summary>
        internal static string Exceptions_Messages_VerificationFailure {
            get {
                return ResourceManager.GetString("Exceptions_Messages_VerificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unload a domain. The name of the domain is: {0}.
        /// </summary>
        internal static string Kernel_LogMessage_DomainUnloadFailed {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_DomainUnloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start kernel service of type [{0}]. Error was {1}..
        /// </summary>
        internal static string Kernel_LogMessage_FailedToStartService_WithTypeAndError {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_FailedToStartService_WithTypeAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop kernel service of type [{0}]. Error was {1}..
        /// </summary>
        internal static string Kernel_LogMessage_FailedToStopService_WithTypeAndError {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_FailedToStopService_WithTypeAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel starting ....
        /// </summary>
        internal static string Kernel_LogMessage_KernelStarting {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_KernelStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel start-up completed..
        /// </summary>
        internal static string Kernel_LogMessage_KernelStartupComplete {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_KernelStartupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel stopped..
        /// </summary>
        internal static string Kernel_LogMessage_KernelStopped {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_KernelStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping kernel ....
        /// </summary>
        internal static string Kernel_LogMessage_KernelStopping {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_KernelStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string Kernel_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service of type {0} failed to disconnect from dependent {1}..
        /// </summary>
        internal static string Kernel_LogMessage_ServiceDisconnectionFailed {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_ServiceDisconnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel service of type [{0}] started..
        /// </summary>
        internal static string Kernel_LogMessage_ServiceStarted_WithType {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_ServiceStarted_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel service of type [{0}] stopped..
        /// </summary>
        internal static string Kernel_LogMessage_ServiceStopped_WithType {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_ServiceStopped_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting kernel service of type [{0}]..
        /// </summary>
        internal static string Kernel_LogMessage_StartingService_WithType {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_StartingService_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping kernel service of type [{0}]..
        /// </summary>
        internal static string Kernel_LogMessage_StoppingService_WithType {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_StoppingService_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log sink was started..
        /// </summary>
        internal static string LogSink_LogMessage_LoggersStarted {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_LoggersStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log sink was stopped..
        /// </summary>
        internal static string LogSink_LogMessage_LoggersStopped {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_LoggersStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string LogSink_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to report the message delivery to {0}. The message [{2}] was send to {1}. The stack trace is: {3}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndException {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndExceptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery of message [{2}] has failed because {3}. The message was send by {0} to {1}..
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was started..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStarted {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was stopped..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStopped {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset activation failed.
        /// </summary>
        internal static string Notifications_FailedToActivateDataset {
            get {
                return ResourceManager.GetString("Notifications_FailedToActivateDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin location process completed..
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanCompleted {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating all the files in {0} failed due to an exception. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanFailed_WithDirectoryAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanFailed_WithDirectoryAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating plugins in {0}..
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanStarted_WithDirectory {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanStarted_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of the plugin assembly {0} failed. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_AssemblyLoadFailed_WithNameAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_AssemblyLoadFailed_WithNameAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting information from Assembly {0} failed. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_TypeScanFailed_WithAssemblyAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_TypeScanFailed_WithAssemblyAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo plugin scan AppDomain.
        /// </summary>
        internal static string Plugins_PluginScanDomainName {
            get {
                return ResourceManager.GetString("Plugins_PluginScanDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating dataset ....
        /// </summary>
        internal static string Progress_ActivatingDataset {
            get {
                return ResourceManager.GetString("Progress_ActivatingDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing current project..
        /// </summary>
        internal static string Project_LogMessage_ClosingProject {
            get {
                return ResourceManager.GetString("Project_LogMessage_ClosingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new dataset with dataset [{0}] as parent..
        /// </summary>
        internal static string Project_LogMessage_CreatingDataset_WithInformation {
            get {
                return ResourceManager.GetString("Project_LogMessage_CreatingDataset_WithInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted dataset [{0}]..
        /// </summary>
        internal static string Project_LogMessage_DeletedDataset_WithId {
            get {
                return ResourceManager.GetString("Project_LogMessage_DeletedDataset_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting dataset [{0}] and all its children..
        /// </summary>
        internal static string Project_LogMessage_DeletingDatasetAndChildren_WithInformation {
            get {
                return ResourceManager.GetString("Project_LogMessage_DeletingDatasetAndChildren_WithInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Projects_Dataset_RootDatasetName {
            get {
                return ResourceManager.GetString("Projects_Dataset_RootDatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dataset contains the default dataset information for the project. Any child dataset will inherit this default information unless it specifies otherwise..
        /// </summary>
        internal static string Projects_Dataset_RootDatasetSummary {
            get {
                return ResourceManager.GetString("Projects_Dataset_RootDatasetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new group [{0}] to composition layer..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_AddingGroup_WithId {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_AddingGroup_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting exporting group [{1}] with importing group [{0}]..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_ConnectingGroups_WithImportAndExport {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_ConnectingGroups_WithImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting all imports and exports from group [{0}]..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_DisconnectingAllFromGroup_WithId {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_DisconnectingAllFromGroup_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting exporting group [{1}] from importing group [{0}]..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_DisconnectingGroups_WithImportAndExport {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_DisconnectingGroups_WithImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading data from remote dataset..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_ReloadingFromDataset {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_ReloadingFromDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing group [{0}] from composition layer..
        /// </summary>
        internal static string ProxyCompositionLayer_LogMessage_RemovingGroup_WithId {
            get {
                return ResourceManager.GetString("ProxyCompositionLayer_LogMessage_RemovingGroup_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new part [{0}] to repository..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_AddingPartToRepository_WithPartInformation {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_AddingPartToRepository_WithPartInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering groups via exporter of type [{0}]..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_RegisteringGroupsViaExporter_WithExporterType {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_RegisteringGroupsViaExporter_WithExporterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning assembly [{0}] for plugins..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_ScanningAssembly_WithName {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_ScanningAssembly_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking user interface command with ID: {0}.
        /// </summary>
        internal static string UserInterface_LogMessage_InvokingCommand_WithId {
            get {
                return ResourceManager.GetString("UserInterface_LogMessage_InvokingCommand_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string UserInterface_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("UserInterface_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to shut down application. Error was: {0}..
        /// </summary>
        internal static string UserInterface_LogMessage_ShutDownFailed_WithError {
            get {
                return ResourceManager.GetString("UserInterface_LogMessage_ShutDownFailed_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received request to shut down application..
        /// </summary>
        internal static string UserInterface_LogMessage_ShuttingDown {
            get {
                return ResourceManager.GetString("UserInterface_LogMessage_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pre-disconnection action failed with an exception. Error information: {0}.
        /// </summary>
        internal static string UserInterrface_LogMessage_DisconnectPreActionFailed {
            get {
                return ResourceManager.GetString("UserInterrface_LogMessage_DisconnectPreActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send a notification of the application start-up completion. Error information: {0}.
        /// </summary>
        internal static string UserInterrface_LogMessage_StartupCompleteNotificationFailed {
            get {
                return ResourceManager.GetString("UserInterrface_LogMessage_StartupCompleteNotificationFailed", resourceCulture);
            }
        }
    }
}
