//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.UI.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.UI.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string DatasetDetailView_Advanced {
            get {
                return ResourceManager.GetString("DatasetDetailView_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on:.
        /// </summary>
        internal static string DatasetDetailView_DatasetEndpoint {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DatasetDetailView_DatasetName {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the dataset here.
        /// </summary>
        internal static string DatasetDetailView_DatasetNameSuggestion {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetNameSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing:.
        /// </summary>
        internal static string DatasetDetailView_DatasetProcessing {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string DatasetDetailView_DatasetSummary {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the summary for the dataset here.
        /// </summary>
        internal static string DatasetDetailView_DatasetSummarySuggestion {
            get {
                return ResourceManager.GetString("DatasetDetailView_DatasetSummarySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to dataset.
        /// </summary>
        internal static string DatasetDetailView_FinishEditing {
            get {
                return ResourceManager.GetString("DatasetDetailView_FinishEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make changes to dataset.
        /// </summary>
        internal static string DatasetDetailView_StartEditing {
            get {
                return ResourceManager.GetString("DatasetDetailView_StartEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        internal static string DatasetDetailView_UnnamedDatasetName {
            get {
                return ResourceManager.GetString("DatasetDetailView_UnnamedDatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for: {0}.
        /// </summary>
        internal static string DatasetDetailView_ViewName {
            get {
                return ResourceManager.GetString("DatasetDetailView_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DatasetGraphView_DatasetName {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the dataset here.
        /// </summary>
        internal static string DatasetGraphView_DatasetNameSuggestion {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetNameSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing:.
        /// </summary>
        internal static string DatasetGraphView_DatasetProcessing {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on:.
        /// </summary>
        internal static string DatasetGraphView_DatasetRunningOn {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetRunningOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored at:.
        /// </summary>
        internal static string DatasetGraphView_DatasetStoredAt {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetStoredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string DatasetGraphView_DatasetSummary {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the summary for the dataset here.
        /// </summary>
        internal static string DatasetGraphView_DatasetSummarySuggestion {
            get {
                return ResourceManager.GetString("DatasetGraphView_DatasetSummarySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details....
        /// </summary>
        internal static string DatasetGraphView_ShowDetail {
            get {
                return ResourceManager.GetString("DatasetGraphView_ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset is not loaded.
        /// </summary>
        internal static string DatasetModel_DatasetIsNotLoaded {
            get {
                return ResourceManager.GetString("DatasetModel_DatasetIsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ErrorReportIconView_Cancel {
            get {
                return ResourceManager.GetString("ErrorReportIconView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ErrorReportIconView_Ok {
            get {
                return ResourceManager.GetString("ErrorReportIconView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items.
        /// </summary>
        internal static string ErrorReportIconView_SelectAll {
            get {
                return ResourceManager.GetString("ErrorReportIconView_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided argument is not suitable for the given function..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentException {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is outside the valid range. Expected a value larger than {0}, got {1}..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_ExpectedLargerThan {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_ExpectedLargerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is outside the valid range. Expected a value smaller than {0}, got {1}..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_ExpectedSmallerThan {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_ExpectedSmallerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the new script was cancelled..
        /// </summary>
        internal static string Exceptions_Messages_CreationOfNewScriptCancelled {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CreationOfNewScriptCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the feedback report to the remote server..
        /// </summary>
        internal static string Exceptions_Messages_FailedToSendFeedbackReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FailedToSendFeedbackReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of the script was cancelled..
        /// </summary>
        internal static string Exceptions_Messages_LoadingOfScriptCancelled {
            get {
                return ResourceManager.GetString("Exceptions_Messages_LoadingOfScriptCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FeedbackIconView_Cancel {
            get {
                return ResourceManager.GetString("FeedbackIconView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string FeedbackIconView_Description {
            get {
                return ResourceManager.GetString("FeedbackIconView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string FeedbackIconView_Ok {
            get {
                return ResourceManager.GetString("FeedbackIconView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in: {0} - Occurred on: {1}.
        /// </summary>
        internal static string FeedbackToTextConverter_FeedbackModel {
            get {
                return ResourceManager.GetString("FeedbackToTextConverter_FeedbackModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Add_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Backward_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Backward_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Backward_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Backward_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Backward_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Backward_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Backward_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Backward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Backward_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Backward_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Bug_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Bug_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cancel_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Cancel_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Copy_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Copy_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Cut_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Cut_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Delete_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Download_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Download_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Forward_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Forward_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Forward_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Forward_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Forward_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Forward_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Forward_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Forward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Forward_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Forward_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_128 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_16 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_24 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_32 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_48 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockClosed_72 {
            get {
                object obj = ResourceManager.GetObject("Img_LockClosed_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_128 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_16 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_24 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_32 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_48 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LockOpen_72 {
            get {
                object obj = ResourceManager.GetObject("Img_LockOpen_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_128 {
            get {
                object obj = ResourceManager.GetObject("Img_New_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_16 {
            get {
                object obj = ResourceManager.GetObject("Img_New_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_24 {
            get {
                object obj = ResourceManager.GetObject("Img_New_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_256 {
            get {
                object obj = ResourceManager.GetObject("Img_New_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_32 {
            get {
                object obj = ResourceManager.GetObject("Img_New_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_New_48 {
            get {
                object obj = ResourceManager.GetObject("Img_New_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Open_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Open_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Paste_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Paste_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Pause_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Pause_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Play_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Play_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Redo_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Redo_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Refresh_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Refresh_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Save_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Save_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Search_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Search_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_SmileyHappy_128 {
            get {
                object obj = ResourceManager.GetObject("Img_SmileyHappy_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_SmileyNeutral_128 {
            get {
                object obj = ResourceManager.GetObject("Img_SmileyNeutral_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_SmileySad_128 {
            get {
                object obj = ResourceManager.GetObject("Img_SmileySad_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Stop_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Stop_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_128 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_16 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_24 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_256 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_32 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_TextDocument_48 {
            get {
                object obj = ResourceManager.GetObject("Img_TextDocument_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Undo_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Undo_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_128 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_16 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_24 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_256 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_32 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Upload_48 {
            get {
                object obj = ResourceManager.GetObject("Img_Upload_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_128 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_16 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_24 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_256 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_32 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomIn_48 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomIn_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_128 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_16 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_24 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_256 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_32 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ZoomOut_48 {
            get {
                object obj = ResourceManager.GetObject("Img_ZoomOut_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MachineSelectorView_Cancel {
            get {
                return ResourceManager.GetString("MachineSelectorView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MachineSelectorView_Ok {
            get {
                return ResourceManager.GetString("MachineSelectorView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving dataset loading proposals.
        ///Please wait ....
        /// </summary>
        internal static string MachineSelectorView_PleaseWait {
            get {
                return ResourceManager.GetString("MachineSelectorView_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a machine for the dataset.
        /// </summary>
        internal static string MachineSelectorView_WindowTitle {
            get {
                return ResourceManager.GetString("MachineSelectorView_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown network resource ....
        /// </summary>
        internal static string NetworkIdentifierToTextConverter_UnknownNetworkResource {
            get {
                return ResourceManager.GetString("NetworkIdentifierToTextConverter_UnknownNetworkResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details....
        /// </summary>
        internal static string ProgressTreeNode_MoreDetails_Text {
            get {
                return ResourceManager.GetString("ProgressTreeNode_MoreDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to pause the data processing.
        /// </summary>
        internal static string ProgressTreeNode_Pause_Hint {
            get {
                return ResourceManager.GetString("ProgressTreeNode_Pause_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to start the data processing.
        /// </summary>
        internal static string ProgressTreeNode_Play_Hint {
            get {
                return ResourceManager.GetString("ProgressTreeNode_Play_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to stop the data processing.
        /// </summary>
        internal static string ProgressTreeNode_Stop_Hint {
            get {
                return ResourceManager.GetString("ProgressTreeNode_Stop_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string ProjectDescriptionView_ProjectName {
            get {
                return ResourceManager.GetString("ProjectDescriptionView_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of your project here.
        /// </summary>
        internal static string ProjectDescriptionView_ProjectNameSuggestion {
            get {
                return ResourceManager.GetString("ProjectDescriptionView_ProjectNameSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of datasets:.
        /// </summary>
        internal static string ProjectDescriptionView_ProjectNumberOfDatasets {
            get {
                return ResourceManager.GetString("ProjectDescriptionView_ProjectNumberOfDatasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string ProjectDescriptionView_ProjectSummary {
            get {
                return ResourceManager.GetString("ProjectDescriptionView_ProjectSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the summary for your project here.
        /// </summary>
        internal static string ProjectDescriptionView_ProjectSummarySuggestion {
            get {
                return ResourceManager.GetString("ProjectDescriptionView_ProjectSummarySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectView_ViewName {
            get {
                return ResourceManager.GetString("ProjectView_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveProjectCommand_HistoryMark {
            get {
                return ResourceManager.GetString("SaveProjectCommand_HistoryMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        internal static string ScriptDescription_Language_IronPython {
            get {
                return ResourceManager.GetString("ScriptDescription_Language_IronPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby.
        /// </summary>
        internal static string ScriptDescription_Language_IronRuby {
            get {
                return ResourceManager.GetString("ScriptDescription_Language_IronRuby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Files | *.{1}.
        /// </summary>
        internal static string ScriptFileExtensionFileFilter {
            get {
                return ResourceManager.GetString("ScriptFileExtensionFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a script file.
        /// </summary>
        internal static string ScriptPresenter_SelectScriptFile {
            get {
                return ResourceManager.GetString("ScriptPresenter_SelectScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ScriptView_Command_CancelRunScript_Name {
            get {
                return ResourceManager.GetString("ScriptView_Command_CancelRunScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ScriptView_Command_CancelRunScript_Text {
            get {
                return ResourceManager.GetString("ScriptView_Command_CancelRunScript_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string ScriptView_Command_RunScript_Name {
            get {
                return ResourceManager.GetString("ScriptView_Command_RunScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string ScriptView_Command_RunScript_Text {
            get {
                return ResourceManager.GetString("ScriptView_Command_RunScript_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script language:.
        /// </summary>
        internal static string ScriptView_CurrentScriptLanguage {
            get {
                return ResourceManager.GetString("ScriptView_CurrentScriptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ScriptView_Output_Menu_Clear {
            get {
                return ResourceManager.GetString("ScriptView_Output_Menu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string ScriptView_ViewName {
            get {
                return ResourceManager.GetString("ScriptView_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SelectScriptLanguageView_Cancel {
            get {
                return ResourceManager.GetString("SelectScriptLanguageView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string SelectScriptLanguageView_Ok {
            get {
                return ResourceManager.GetString("SelectScriptLanguageView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a script language.
        /// </summary>
        internal static string SelectScriptLanguageView_WindowTitle {
            get {
                return ResourceManager.GetString("SelectScriptLanguageView_WindowTitle", resourceCulture);
            }
        }
    }
}
