//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument value was outside the valid range. The argument value was: {0}.
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command context does not allow a result to be returned..
        /// </summary>
        internal static string Exceptions_Messages_CannotReturnAResult {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotReturnAResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the specified name has already been defined..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateCommand {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the name [{0}] has already been defined..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateCommand_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateCommand_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare these two objects, their types do not match [this: {0}; other: {1}].
        /// </summary>
        internal static string Exceptions_Messages_ErrorCode_CompareArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ErrorCode_CompareArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result type..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectResultType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result type. Got {0} but expected {1}..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectResultType_WithTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectResultType_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress needs to be {0}% or smaller..
        /// </summary>
        internal static string Exceptions_Messages_ProgressToLarge {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProgressToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress needs to be {0}% or larger..
        /// </summary>
        internal static string Exceptions_Messages_ProgressToSmall {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProgressToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command with the specified name could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommand {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command with the name [{0}] could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommand_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommand_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter with the specified name could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommandParameter {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter with the name [{0}] could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommandParameter_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommandParameter_WithName", resourceCulture);
            }
        }
    }
}
