//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument value was outside the valid range. The argument value was: {0}.
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete an object from the timeline before its creation..
        /// </summary>
        internal static string Exceptions_Messages_CannotDeleteObjectBeforeCreation {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotDeleteObjectBeforeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move to a point in time prior to the beginning of the known timeline..
        /// </summary>
        internal static string Exceptions_Messages_CannotMovePastBeginningOfTime {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotMovePastBeginningOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move to a point in time past the end of the known timeline..
        /// </summary>
        internal static string Exceptions_Messages_CannotMovePastEndingOfTime {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotMovePastEndingOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object must be alive in order to be removed..
        /// </summary>
        internal static string Exceptions_Messages_CannotRemoveNonLivingObject {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotRemoveNonLivingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command context does not allow a result to be returned..
        /// </summary>
        internal static string Exceptions_Messages_CannotReturnAResult {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotReturnAResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot roll-back to a point in the future..
        /// </summary>
        internal static string Exceptions_Messages_CannotRollBackToAPointInTheFuture {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotRollBackToAPointInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot roll-forward to a point in the past..
        /// </summary>
        internal static string Exceptions_Messages_CannotRollForwardToAPointInThePast {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotRollForwardToAPointInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values may be stored on the first point in time..
        /// </summary>
        internal static string Exceptions_Messages_CannotStoreValuesAtTheStartOfTime {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotStoreValuesAtTheStartOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A marker must be set before starting the timer..
        /// </summary>
        internal static string Exceptions_Messages_CurrentProgressMarkNotSet {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CurrentProgressMarkNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the specified name has already been defined..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateCommand {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the name [{0}] has already been defined..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateCommand_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateCommand_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare these two objects, their types do not match [this: {0}; other: {1}].
        /// </summary>
        internal static string Exceptions_Messages_ErrorCode_CompareArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ErrorCode_CompareArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided history ID does not match with the expected history ID..
        /// </summary>
        internal static string Exceptions_Messages_HistoryIdDoesNotMatch {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HistoryIdDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history ID {0} does not match with the history ID {1} that was provided earlier..
        /// </summary>
        internal static string Exceptions_Messages_HistoryIdDoesNotMatch_WithIds {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HistoryIdDoesNotMatch_WithIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result type..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectResultType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result type. Got {0} but expected {1}..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectResultType_WithTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectResultType_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided time marker is not valid in the current situation..
        /// </summary>
        internal static string Exceptions_Messages_InvalidTimeMarker {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidTimeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value later in time has been registered..
        /// </summary>
        internal static string Exceptions_Messages_NoFutureValueRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoFutureValueRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value earlier in time has been registered..
        /// </summary>
        internal static string Exceptions_Messages_NoPreviousValueRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoPreviousValueRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object has already been created for this timeline..
        /// </summary>
        internal static string Exceptions_Messages_ObjectHasAlreadyBeenCreated {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ObjectHasAlreadyBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is invalid because the object has not been created yet..
        /// </summary>
        internal static string Exceptions_Messages_ObjectHasNotBeenCreatedYet {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ObjectHasNotBeenCreatedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with the specified history ID does not exist in the current timeline..
        /// </summary>
        internal static string Exceptions_Messages_ObjectUnknownToTimeline {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ObjectUnknownToTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with history ID {0} does not exist in the current timeline..
        /// </summary>
        internal static string Exceptions_Messages_ObjectUnknownToTimeline_WithId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ObjectUnknownToTimeline_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress needs to be {0}% or smaller..
        /// </summary>
        internal static string Exceptions_Messages_ProgressToLarge {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProgressToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress needs to be {0}% or larger..
        /// </summary>
        internal static string Exceptions_Messages_ProgressToSmall {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProgressToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array to which the values should be copied is shorter ({0}) than the number of items to be copied ({1})..
        /// </summary>
        internal static string Exceptions_Messages_TheArrayIsShorterThanTheNumberOfItems_WithValues {
            get {
                return ResourceManager.GetString("Exceptions_Messages_TheArrayIsShorterThanTheNumberOfItems_WithValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform a roll-back due to a blocking dependency..
        /// </summary>
        internal static string Exceptions_Messages_UnableToPerformRollBackDueToBlockingDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnableToPerformRollBackDueToBlockingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform a roll-forward due to a blocking dependency..
        /// </summary>
        internal static string Exceptions_Messages_UnableToPerformRollForwardDueToBlockingDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnableToPerformRollForwardDueToBlockingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command with the specified name could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommand {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command with the name [{0}] could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommand_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommand_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter with the specified name could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommandParameter {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter with the name [{0}] could be found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownCommandParameter_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownCommandParameter_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name does not belong to a known time marker..
        /// </summary>
        internal static string Exceptions_Messages_UnknownTimeMarker {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownTimeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name ({0}) does not belong to a known time marker..
        /// </summary>
        internal static string Exceptions_Messages_UnknownTimeMarker_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownTimeMarker_WithName", resourceCulture);
            }
        }
    }
}
