//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Core.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Core.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A channel type must inherit from IChannelType..
        /// </summary>
        internal static string Exceptions_Messages_AChannelTypeMustDeriveFromIChannelType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AChannelTypeMustDeriveFromIChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A disk cannot have more free space than total space..
        /// </summary>
        internal static string Exceptions_Messages_ADiskCannotHaveMoreFreeSpaceThanTotalSpace {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ADiskCannotHaveMoreFreeSpaceThanTotalSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A disk needs to have a serial number..
        /// </summary>
        internal static string Exceptions_Messages_ADiskNeedsToHaveASerial {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ADiskNeedsToHaveASerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A machine needs at least one disk..
        /// </summary>
        internal static string Exceptions_Messages_AMachineNeedsAtLeastOneDisk {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AMachineNeedsAtLeastOneDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A machine needs at least one processor..
        /// </summary>
        internal static string Exceptions_Messages_AMachineNeedsAtLeastOneProcessor {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AMachineNeedsAtLeastOneProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message must have an ID number. It cannot have the None ID as ID..
        /// </summary>
        internal static string Exceptions_Messages_AMessageNeedsToHaveAnId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AMessageNeedsToHaveAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network connection needs to have a valid MAC address..
        /// </summary>
        internal static string Exceptions_Messages_ANetworkConnectionNeedsAValidMacAddress {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ANetworkConnectionNeedsAValidMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for a base line ID must not be smaller than that of the ID for an unknown value..
        /// </summary>
        internal static string Exceptions_Messages_BaseLineIdValueMustNotBeLessThanTheUnknownIdValue {
            get {
                return ResourceManager.GetString("Exceptions_Messages_BaseLineIdValueMustNotBeLessThanTheUnknownIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dataset cannot be created without a creator..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateDatasetWithoutCreator {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateDatasetWithoutCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset cannot be made a parent..
        /// </summary>
        internal static string Exceptions_Messages_DatasetCannotBecomeParent {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DatasetCannotBecomeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset with ID: {0} cannot be made a parent..
        /// </summary>
        internal static string Exceptions_Messages_DatasetCannotBecomeParent_WithId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DatasetCannotBecomeParent_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the message..
        /// </summary>
        internal static string Exceptions_Messages_FailedToSendMessage {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FailedToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file path cannot be an empty string..
        /// </summary>
        internal static string Exceptions_Messages_FilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring the information from the stream requires a different set of information than provided. The method required {0} but was provided with {1}..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectStreamTransferInformationObjectFound_WithTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectStreamTransferInformationObjectFound_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain name of a machine must not be an empty string..
        /// </summary>
        internal static string Exceptions_Messages_MachineDomainNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MachineDomainNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of a dataset distribution range must be equal or larger than the minimum. The minimum was {0} and the maximum was {1}..
        /// </summary>
        internal static string Exceptions_Messages_MaximumDistributionRangeMustBeLargerThanMinimum_WithValues {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MaximumDistributionRangeMustBeLargerThanMinimum_WithValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum of a dataset distribution range must be equal or larger than one. The given value is {0}..
        /// </summary>
        internal static string Exceptions_Messages_MimimumDistributionRangeMustBeLargerThanOne_WithValue {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MimimumDistributionRangeMustBeLargerThanOne_WithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of logical processors in a CPU must be equal or larger than the number of physical cores..
        /// </summary>
        internal static string Exceptions_Messages_NumberOfLogicalProcessorsMustBeLargerOrEqualToNumberOfPhysicalCores {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NumberOfLogicalProcessorsMustBeLargerOrEqualToNumberOfPhysica" +
                        "lCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of physical cores in a CPU must be larger than zero..
        /// </summary>
        internal static string Exceptions_Messages_NumberOfPhysicalCoresMustBeLargerThanZero {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NumberOfPhysicalCoresMustBeLargerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address width of a CPU needs to be larger than zero. Most common values are 32 for x86 and 64 for x64..
        /// </summary>
        internal static string Exceptions_Messages_ProcessorAddressWidthMustBeLargerThanZero {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProcessorAddressWidthMustBeLargerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock speed of a CPU must be larger than zero..
        /// </summary>
        internal static string Exceptions_Messages_ProcessorClockSpeedMustBeLargerThanZero {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ProcessorClockSpeedMustBeLargerThanZero", resourceCulture);
            }
        }
    }
}
