//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.ProjectExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.ProjectExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutBanner_Png {
            get {
                object obj = ResourceManager.GetObject("AboutBanner_Png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AboutWindow_Close {
            get {
                return ResourceManager.GetString("AboutWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Apollo Project Explorer.
        /// </summary>
        internal static string Application_Name_FileOpen {
            get {
                return ResourceManager.GetString("Application_Name_FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo Project Explorer.
        /// </summary>
        internal static string Application_Name_NoFileOpen {
            get {
                return ResourceManager.GetString("Application_Name_NoFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range. The argument value was: {0}..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to log a message if the LogLevel is set to None..
        /// </summary>
        internal static string Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. The error code is: {0}. Please contact your vendor..
        /// </summary>
        internal static string Exceptions_Messages_InternalError_WithCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InternalError_WithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified progress mark is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownProgressMark {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownProgressMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The progress mark [{0}] is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownProgressMark_WithMark {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownProgressMark_WithMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string MainWindow_Menu_Edit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        internal static string MainWindow_Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        internal static string MainWindow_Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string MainWindow_Menu_File_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        internal static string MainWindow_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run.
        /// </summary>
        internal static string MainWindow_Menu_Run {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project.
        /// </summary>
        internal static string MainWindow_Menu_View_Projects {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Script.
        /// </summary>
        internal static string MainWindow_Menu_View_Script {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_tart page.
        /// </summary>
        internal static string MainWindow_Menu_View_StartPage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        internal static string MainWindow_Menu_Window {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project explorer.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close page after project load.
        /// </summary>
        internal static string WelcomeView_ClosePageAfterProjectLoad {
            get {
                return ResourceManager.GetString("WelcomeView_ClosePageAfterProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to grips with datasets.
        /// </summary>
        internal static string WelcomeView_Content_GettingStarted_AboutDatasetsTab_Header {
            get {
                return ResourceManager.GetString("WelcomeView_Content_GettingStarted_AboutDatasetsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a project.
        /// </summary>
        internal static string WelcomeView_Content_GettingStarted_AboutProjectsTab_Header {
            get {
                return ResourceManager.GetString("WelcomeView_Content_GettingStarted_AboutProjectsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting away.
        /// </summary>
        internal static string WelcomeView_Content_GettingStarted_AboutScriptsTab_Header {
            get {
                return ResourceManager.GetString("WelcomeView_Content_GettingStarted_AboutScriptsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        internal static string WelcomeView_Content_GettingStartedTab_Header {
            get {
                return ResourceManager.GetString("WelcomeView_Content_GettingStartedTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news.
        /// </summary>
        internal static string WelcomeView_Content_LatestNewsTab_Header {
            get {
                return ResourceManager.GetString("WelcomeView_Content_LatestNewsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string WelcomeView_NewProject {
            get {
                return ResourceManager.GetString("WelcomeView_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project....
        /// </summary>
        internal static string WelcomeView_OpenProject {
            get {
                return ResourceManager.GetString("WelcomeView_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string WelcomeView_Recent {
            get {
                return ResourceManager.GetString("WelcomeView_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page on startup.
        /// </summary>
        internal static string WelcomeView_ShowPageOnStartup {
            get {
                return ResourceManager.GetString("WelcomeView_ShowPageOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string WelcomeView_Start {
            get {
                return ResourceManager.GetString("WelcomeView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        internal static string WelcomeView_ViewName {
            get {
                return ResourceManager.GetString("WelcomeView_ViewName", resourceCulture);
            }
        }
    }
}
