//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.UI.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.UI.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out the command line options..
        /// </summary>
        internal static string CommandLine_Options_Help_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?|h|help.
        /// </summary>
        internal static string CommandLine_Options_Help_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path of the {FILE} that contains the script..
        /// </summary>
        internal static string CommandLine_Options_ScriptFile_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_ScriptFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s=|script=.
        /// </summary>
        internal static string CommandLine_Options_ScriptFile_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_ScriptFile_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range. The argument value was: {0}..
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to log a message if the LogLevel is set to None..
        /// </summary>
        internal static string Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotLogMessageWithLogLevelSetToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. The error code is: {0}. Please contact your vendor..
        /// </summary>
        internal static string Exceptions_Messages_InternalError_WithCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InternalError_WithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license verification has failed. Please contact your vendor..
        /// </summary>
        internal static string Exceptions_Messages_VerificationFailure {
            get {
                return ResourceManager.GetString("Exceptions_Messages_VerificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo script runner ({0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: apollo.UI.console.exe [OPTIONS].
        /// </summary>
        internal static string Help_Usage_Intro {
            get {
                return ResourceManager.GetString("Help_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the input parameters. Exception was: {0}.
        /// </summary>
        internal static string Log_Error_InvalidInputParameters_WithException {
            get {
                return ResourceManager.GetString("Log_Error_InvalidInputParameters_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while excuting the script. Exception was: {0}.
        /// </summary>
        internal static string Log_Error_ProcessingError_WithException {
            get {
                return ResourceManager.GetString("Log_Error_ProcessingError_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided script file does not exist. File should be at: {0}.
        /// </summary>
        internal static string Log_Error_ScripFileDoesNotExist {
            get {
                return ResourceManager.GetString("Log_Error_ScripFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo.UI.Console - Version: {0}.
        /// </summary>
        internal static string Log_Information_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Log_Information_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file path: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterScriptFile {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input parameters were not valid..
        /// </summary>
        internal static string Output_Error_InvalidInput {
            get {
                return ResourceManager.GetString("Output_Error_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided script file does not exist..
        /// </summary>
        internal static string Output_Error_ScriptFileDoesNotExist {
            get {
                return ResourceManager.GetString("Output_Error_ScriptFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing the script. Please see the log for more information..
        /// </summary>
        internal static string Output_Error_WhileProcessing {
            get {
                return ResourceManager.GetString("Output_Error_WhileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing script. To cancel press Ctrl +C..
        /// </summary>
        internal static string Output_Information_ExecutingScript {
            get {
                return ResourceManager.GetString("Output_Information_ExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading script file ....
        /// </summary>
        internal static string Output_Information_LoadingScriptFile {
            get {
                return ResourceManager.GetString("Output_Information_LoadingScriptFile", resourceCulture);
            }
        }
    }
}
