//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid ID number..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateAMessageWithoutId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateAMessageWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid sender name..
        /// </summary>
        internal static string Exceptions_Messages_CannotCreateAMessageWithoutSender {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotCreateAMessageWithoutSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message where both the sender and the recipient are the same..
        /// </summary>
        internal static string Exceptions_Messages_CannotSendAMessageBackToTheSender {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotSendAMessageBackToTheSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message that is send to nobody..
        /// </summary>
        internal static string Exceptions_Messages_CannotSendAMessageToNoService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotSendAMessageToNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot uninstall the service. The provided service is not the service which is installed. Please use the original service when uninstalling..
        /// </summary>
        internal static string Exceptions_Messages_CannotUninstallNonEquivalentService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotUninstallNonEquivalentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateDnsName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name. The name is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_DuplicateDnsName_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is incorrect. Expected {0}, got {1}..
        /// </summary>
        internal static string Exceptions_Messages_IncorrectType_WithTypes {
            get {
                return ResourceManager.GetString("Exceptions_Messages_IncorrectType_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service failed..
        /// </summary>
        internal static string Exceptions_Messages_KernelServiceStartupFailed {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelServiceStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service of type {0} failed..
        /// </summary>
        internal static string Exceptions_Messages_KernelServiceStartupFailed_WithService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelServiceStartupFailed_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency..
        /// </summary>
        internal static string Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency. Service of type {0} missed a dependency..
        /// </summary>
        internal static string Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel service failed due to a missing a dependency..
        /// </summary>
        internal static string Exceptions_Messages_MissingServiceDependency {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no known message pipeline object..
        /// </summary>
        internal static string Exceptions_Messages_PipelineObjectMissing {
            get {
                return ResourceManager.GetString("Exceptions_Messages_PipelineObjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender DNS name cannot be equivalent to the Nobody DNS name.
        /// </summary>
        internal static string Exceptions_Messages_SenderCannotBeNobody {
            get {
                return ResourceManager.GetString("Exceptions_Messages_SenderCannotBeNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have the KernelService type as dependency..
        /// </summary>
        internal static string Exceptions_Messages_ServiceCannotDependOnGenericKernelService {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceCannotDependOnGenericKernelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have its own type as dependency..
        /// </summary>
        internal static string Exceptions_Messages_ServiceCannotDependOnItself {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceCannotDependOnItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service object of the given type is already installed..
        /// </summary>
        internal static string Exceptions_Messages_ServiceTypeAlreadyInstalled {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ServiceTypeAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown..
        /// </summary>
        internal static string Exceptions_Messages_UnknownDnsName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown. The name is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_UnknownDnsName_WithName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel service of the given type is installed..
        /// </summary>
        internal static string Exceptions_Messages_UnknownKernelServiceType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownKernelServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to report the message delivery to {0}. The message [{2}] was send to {1}. The stack trace is: {3}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndException {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndExceptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery of message [{2}] has failed because {3}. The message was send by {0} to {1}..
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was started..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStarted {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was stopped..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStopped {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderRemoved", resourceCulture);
            }
        }
    }
}
