//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_NonTranslatable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_NonTranslatable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Core.Properties.Resources.NonTranslatable", typeof(Resources_NonTranslatable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range..
        /// </summary>
        internal static string Exception_Messages_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Exception_Messages_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument was not inside the valid range. The argument value was: {0}..
        /// </summary>
        internal static string Exception_Messages_ArgumentOutOfRange_WithArgument {
            get {
                return ResourceManager.GetString("Exception_Messages_ArgumentOutOfRange_WithArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare these objects: {0} and {1}.
        /// </summary>
        internal static string Exception_Messages_CannotCompareUnequalTypes {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotCompareUnequalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid ID number..
        /// </summary>
        internal static string Exception_Messages_CannotCreateAMessageWithoutId {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotCreateAMessageWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message with no or an invalid sender name..
        /// </summary>
        internal static string Exception_Messages_CannotCreateAMessageWithoutSender {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotCreateAMessageWithoutSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of the application does not allow the creation of a new project..
        /// </summary>
        internal static string Exception_Messages_CannotCreateNewProject {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotCreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a project without a dataset distribution function..
        /// </summary>
        internal static string Exception_Messages_CannotCreateProjectWithoutDatasetDistributor {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotCreateProjectWithoutDatasetDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified dataset cannot be deleted..
        /// </summary>
        internal static string Exception_Messages_CannotDeleteDataset {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotDeleteDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified dataset (with ID: {0}) cannot be deleted..
        /// </summary>
        internal static string Exception_Messages_CannotDeleteDataset_WithDatasetId {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotDeleteDataset_WithDatasetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to load a dataset on zero machines..
        /// </summary>
        internal static string Exception_Messages_CannotLoadDatasetOnNoMachines {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotLoadDatasetOnNoMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dataset cannot be loaded without a preferred loading location..
        /// </summary>
        internal static string Exception_Messages_CannotLoadDatasetWithoutLoadingLocation {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotLoadDatasetWithoutLoadingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of the application does not allow the loading of an existing project..
        /// </summary>
        internal static string Exception_Messages_CannotLoadProject {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to log a message if the LogLevel is set to None..
        /// </summary>
        internal static string Exception_Messages_CannotLogMessageWithLogLevelSetToNone {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotLogMessageWithLogLevelSetToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message where both the sender and the recipient are the same. The provided name was {0}..
        /// </summary>
        internal static string Exception_Messages_CannotSendAMessageBackToTheSender_WithDnsName {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotSendAMessageBackToTheSender_WithDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a message that is send to nobody..
        /// </summary>
        internal static string Exception_Messages_CannotSendAMessageToNoService {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotSendAMessageToNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot uninstall the service. The provided service is not the service which is installed. Please use the original service when uninstalling..
        /// </summary>
        internal static string Exception_Messages_CannotUninstallNonEquivalentService {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotUninstallNonEquivalentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current project cannot be unloaded..
        /// </summary>
        internal static string Exception_Messages_CannotUnloadProject {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotUnloadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project cannot be used after it has been closed..
        /// </summary>
        internal static string Exception_Messages_CannotUseProjectAfterClosingIt {
            get {
                return ResourceManager.GetString("Exception_Messages_CannotUseProjectAfterClosingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset with ID: {0} cannot be made a parent..
        /// </summary>
        internal static string Exception_Messages_DatasetCannotBecomeParent_WithId {
            get {
                return ResourceManager.GetString("Exception_Messages_DatasetCannotBecomeParent_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name..
        /// </summary>
        internal static string Exception_Messages_DuplicateDnsName {
            get {
                return ResourceManager.GetString("Exception_Messages_DuplicateDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is a duplicate of another DNS name. The name is: {0}.
        /// </summary>
        internal static string Exception_Messages_DuplicateDnsName_WithName {
            get {
                return ResourceManager.GetString("Exception_Messages_DuplicateDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a new project failed..
        /// </summary>
        internal static string Exception_Messages_FailedToCreateProject {
            get {
                return ResourceManager.GetString("Exception_Messages_FailedToCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of the specified project failed..
        /// </summary>
        internal static string Exception_Messages_FailedToLoadProject {
            get {
                return ResourceManager.GetString("Exception_Messages_FailedToLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write a log entry for log type: {0}.
        /// </summary>
        internal static string Exception_Messages_IncorrectLogType {
            get {
                return ResourceManager.GetString("Exception_Messages_IncorrectLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is incorrect. Expected {0}, got {1}..
        /// </summary>
        internal static string Exception_Messages_IncorrectType_WithTypes {
            get {
                return ResourceManager.GetString("Exception_Messages_IncorrectType_WithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. The error code is: {0}. Please contact your vendor..
        /// </summary>
        internal static string Exception_Messages_InternalError_WithCode {
            get {
                return ResourceManager.GetString("Exception_Messages_InternalError_WithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service failed..
        /// </summary>
        internal static string Exception_Messages_KernelServiceStartupFailed {
            get {
                return ResourceManager.GetString("Exception_Messages_KernelServiceStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of a service of type {0} failed..
        /// </summary>
        internal static string Exception_Messages_KernelServiceStartupFailed_WithService {
            get {
                return ResourceManager.GetString("Exception_Messages_KernelServiceStartupFailed_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency..
        /// </summary>
        internal static string Exception_Messages_KernelStartupFailedDueToMissingServiceDependency {
            get {
                return ResourceManager.GetString("Exception_Messages_KernelStartupFailedDueToMissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup of the kernel failed due to a missing service dependency. Service of type {0} missed a dependency..
        /// </summary>
        internal static string Exception_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService {
            get {
                return ResourceManager.GetString("Exception_Messages_KernelStartupFailedDueToMissingServiceDependency_WithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified log type has no logger registered..
        /// </summary>
        internal static string Exception_Messages_LogTypeHasNoLogger {
            get {
                return ResourceManager.GetString("Exception_Messages_LogTypeHasNoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log type {0} has no logger registered..
        /// </summary>
        internal static string Exception_Messages_LogTypeHasNoLogger_WithLogType {
            get {
                return ResourceManager.GetString("Exception_Messages_LogTypeHasNoLogger_WithLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create one or more dataset without creation information..
        /// </summary>
        internal static string Exception_Messages_MissingCreationInformation {
            get {
                return ResourceManager.GetString("Exception_Messages_MissingCreationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no notification action registered for the given notification name..
        /// </summary>
        internal static string Exception_Messages_MissingNotificationAction {
            get {
                return ResourceManager.GetString("Exception_Messages_MissingNotificationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no notification action registered for the notification with name {0}..
        /// </summary>
        internal static string Exception_Messages_MissingNotificationAction_WithName {
            get {
                return ResourceManager.GetString("Exception_Messages_MissingNotificationAction_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A missing service dependency was detected. The requested action cannot be performed..
        /// </summary>
        internal static string Exception_Messages_MissingServiceDependency {
            get {
                return ResourceManager.GetString("Exception_Messages_MissingServiceDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be at least size of 1..
        /// </summary>
        internal static string Exception_Messages_MustBufferMoreThanZeroMessages {
            get {
                return ResourceManager.GetString("Exception_Messages_MustBufferMoreThanZeroMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be at least size of 1. The specified size was {0}..
        /// </summary>
        internal static string Exception_Messages_MustBufferMoreThanZeroMessages_WithCount {
            get {
                return ResourceManager.GetString("Exception_Messages_MustBufferMoreThanZeroMessages_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time step for buffer flushing must be a positive number larger than zero. The specified time step was {0}..
        /// </summary>
        internal static string Exception_Messages_MustFlushAfterPositiveTimestep_WithTimestep {
            get {
                return ResourceManager.GetString("Exception_Messages_MustFlushAfterPositiveTimestep_WithTimestep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current project. It is not possible to adjust the properties of the current project or any of its datasets..
        /// </summary>
        internal static string Exception_Messages_NoCurrentProject {
            get {
                return ResourceManager.GetString("Exception_Messages_NoCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no known message pipeline object..
        /// </summary>
        internal static string Exception_Messages_PipelineObjectMissing {
            get {
                return ResourceManager.GetString("Exception_Messages_PipelineObjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender DNS name cannot be equivalent to the Nobody DNS name.
        /// </summary>
        internal static string Exception_Messages_SenderCannotBeNobody {
            get {
                return ResourceManager.GetString("Exception_Messages_SenderCannotBeNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have the KernelService type as dependency..
        /// </summary>
        internal static string Exception_Messages_ServiceCannotDependOnGenericKernelService {
            get {
                return ResourceManager.GetString("Exception_Messages_ServiceCannotDependOnGenericKernelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kernel service cannot have its own type as dependency..
        /// </summary>
        internal static string Exception_Messages_ServiceCannotDependOnItself {
            get {
                return ResourceManager.GetString("Exception_Messages_ServiceCannotDependOnItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service tried to perform an action while it was not in a working state. The actual state was: {0}.
        /// </summary>
        internal static string Exception_Messages_ServicesIsNotFullyFunctional {
            get {
                return ResourceManager.GetString("Exception_Messages_ServicesIsNotFullyFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service object of the given type is already installed..
        /// </summary>
        internal static string Exception_Messages_ServiceTypeAlreadyInstalled {
            get {
                return ResourceManager.GetString("Exception_Messages_ServiceTypeAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset is unknown..
        /// </summary>
        internal static string Exception_Messages_UnknownDataset {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given dataset with ID: {0} is unknown..
        /// </summary>
        internal static string Exception_Messages_UnknownDataset_WithId {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownDataset_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown..
        /// </summary>
        internal static string Exception_Messages_UnknownDnsName {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DNS name is unknown. The name is: {0}.
        /// </summary>
        internal static string Exception_Messages_UnknownDnsName_WithName {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownDnsName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernel service of the given type is installed..
        /// </summary>
        internal static string Exception_Messages_UnknownKernelServiceType {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownKernelServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified notification name is a duplicate of another notification name..
        /// </summary>
        internal static string Exception_Messages_UnknownNotificationName {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownNotificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified notification name is a duplicate of another notification name. The name is {0}..
        /// </summary>
        internal static string Exception_Messages_UnknownNotificationName_WithName {
            get {
                return ResourceManager.GetString("Exception_Messages_UnknownNotificationName_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license verification has failed. Please contact your vendor..
        /// </summary>
        internal static string Exception_Messages_VerificationFailure {
            get {
                return ResourceManager.GetString("Exception_Messages_VerificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unload a domain. The name of the domain is: {0}.
        /// </summary>
        internal static string Kernel_LogMessage_DomainUnloadFailed {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_DomainUnloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string Kernel_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service of type {0} failed to disconnect from dependent {1}..
        /// </summary>
        internal static string Kernel_LogMessage_ServiceDisconnectionFailed {
            get {
                return ResourceManager.GetString("Kernel_LogMessage_ServiceDisconnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log sink was started..
        /// </summary>
        internal static string LogSink_LogMessage_LoggersStarted {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_LoggersStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log sink was stopped..
        /// </summary>
        internal static string LogSink_LogMessage_LoggersStopped {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_LoggersStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string LogSink_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("LogSink_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message listener object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_ListenerRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_ListenerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to report the message delivery to {0}. The message [{2}] was send to {1}. The stack trace is: {3}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndException {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndExceptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery of message [{2}] has failed because {3}. The message was send by {0} to {1}..
        /// </summary>
        internal static string MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_MessageDeliveryFailed_WithSenderRecipientIdAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was started..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStarted {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message pipeline was stopped..
        /// </summary>
        internal static string MessagePipeline_LogMessage_PipelineStopped {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_PipelineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was added with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderAdded {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message sender object was removed with name: {0}.
        /// </summary>
        internal static string MessagePipeline_LogMessage_SenderRemoved {
            get {
                return ResourceManager.GetString("MessagePipeline_LogMessage_SenderRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while sending a message. Exception information is: {0}.
        /// </summary>
        internal static string UserInterface_LogMessage_MessageSendExceptionOccurred {
            get {
                return ResourceManager.GetString("UserInterface_LogMessage_MessageSendExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pre-disconnection action failed with an exception. Error information: {0}.
        /// </summary>
        internal static string UserInterrface_LogMessage_DisconnectPreActionFailed {
            get {
                return ResourceManager.GetString("UserInterrface_LogMessage_DisconnectPreActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send a notification of the application start-up completion. Error information: {0}.
        /// </summary>
        internal static string UserInterrface_LogMessage_StartupCompleteNotificationFailed {
            get {
                return ResourceManager.GetString("UserInterrface_LogMessage_StartupCompleteNotificationFailed", resourceCulture);
            }
        }
    }
}
