//-----------------------------------------------------------------------
// <copyright company="P. van der Velde">
//     Copyright (c) P. van der Velde. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System;

namespace Apollo.Utils.Licensing
{
    /// <summary>
    /// A delegate used to set the latest license verification results.
    /// </summary>
    /// <param name="checksum">The checksum that was generated by combining the original checksum and the result.</param>
    /// <param name="expirationTime">The time after which the current result is considered expired.</param>
    internal delegate void LicenseResultUpdated(Checksum checksum, DateTimeOffset expirationTime);
}
